baseURL = "https://labs.ialhasan.com/"
languageCode = "en-us"
title = "معامل الحسن"
theme = "minimal-arabic"

[params]
# Warning Keys are case sensitives
Subtitle = "مشاريع تقنية مفتوحة المصدر"
description = "مشاريع تقنية مفتوحة المصدر"
cover = "/images/cover.jpg"
# github = "ialhasan"
aboutme = "https://ialhasan.com"
paginate = 1
logo = "/images/labs.png"